### ISSUE TITLE
Will not download.

### ISSUE THREAD

**Issue by stampylongr** [JohnDeved/megacrypt.js#13]
Hello. I have got everything up and running, but it will not download anything. Here is my server output:

![screenshot 2019-03-05 at 3 31 25 pm](https://user-images.githubusercontent.com/42777835/53835534-be5f4800-3f5b-11e9-958b-b8cd04fded51.png)
What is wrong with it?

And for reference, my server ip is [192.241.133.115](http://192.241.133.115/).

**Comment by RedTiger9** [comment]
I neither cannot downloading anymore :(

**Comment by stampylongr** [comment]
@RedTiger9 for some reason its was acting up, just use https://megacryptapp.herokuapp.com

**Comment by RedTiger9** [comment]
> @RedTiger9 for some reason its was acting up, just use https://megacryptapp.herokuapp.com

Neither works when I click the send buttom. Will I have to open the console with npm start or not?
Thank you.

**Comment by stampylongr** [comment]
@RedTiger9 it's because of the new mega url style, i'll see what i can do

**Comment by RedTiger9** [comment]
> @RedTiger9 it's because of the new mega url style, i'll see what i can do

Thanks!!

**Comment by BugEraser** [comment]
> @RedTiger9 it's because of the new mega url style, i'll see what i can do
Any news?
