### ISSUE TITLE
Is port should be required also in here?

### ISSUE THREAD

**Issue by Lyfv** [JohnDeved/megacrypt.js#2]
https://github.com/JohnDeved/megacrypt.js/blob/59d6e293571534f30fb9f270687888b42d1490f3/modules/megacrypt.js#L20

it should be 
```javascript
response.link = `http://${host}:${config.port}/dl/_/${base64url.escape(link)}`
```

**Comment by SwarShah** [comment]
@Lyfv I also noticed this. You should open PR with the changes.

**Comment by JohnDeved** [comment]
nice catch. i must have overlooked that while i was testing the pullrequest. 
- fixed
